version: "3.9"

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always
